#!/usr/bin/env python3
# Generate genimage.cfg from partition JSON for Android builds
# Based on Spacemit Buildroot scripts/gen_imgcfg.py

import json
import sys
import os

def generate_genimage_cfg(name, partitions):
    cfg_content = '''
# This is a genimage configuration file auto generated by gen_imgcfg.py.
# require genimage version 16

'''
    cfg_content += 'image %s {\n' % name
    cfg_content += '''    hdimage {
        partition-table-type = gpt
    }
'''

    for partition in partitions:
        part_name = partition.get("name", "")
        src_size = partition.get("size", "")
        hidden = partition.get("hidden", False)
        visible = "true"
        if hidden == True:
            visible = "false"
        if src_size == "-":
            src_size = ""
        offset = partition.get("offset", "")
        image = partition.get("image", "")
        holes = partition.get("holes", "{}")

        cfg_content += f'''
    partition {part_name} {{
            image = "{image}"
            offset = "{offset}"
            size = "{src_size}"
            holes = {holes}
            in-partition-table = "{visible}"
    }}
'''

    cfg_content += '''
}

'''

    return cfg_content


def main():
    json_file = "partition_android.json"
    image_name = "android-sdcard.img"
    cfg_file = "genimage.cfg"

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "-i":
            json_file = args[i+1]
            i += 2
        elif args[i] == "-n":
            image_name = args[i+1]
            i += 2
        elif args[i] == "-o":
            cfg_file = args[i+1]
            i += 2
        elif args[i] in ["-h", "--help"]:
            print(f"Usage: {sys.argv[0]} [-i <partitions json file>] [-n <image name>] [-o <cfg file>]")
            sys.exit(0)
        else:
            print(f"Unknown argument: {args[i]}")
            print(f"Usage: {sys.argv[0]} [-i <partitions json file>] [-n <image name>] [-o <cfg file>]")
            sys.exit(1)

    try:
        with open(json_file, 'r') as file:
            cfg_content = json.load(file)

        partitions = cfg_content["partitions"]
        genimage_cfg = generate_genimage_cfg(image_name, partitions)
    except FileNotFoundError:
        print(f"File not found: {json_file}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        sys.exit(1)

    with open(cfg_file, "w") as f:
        f.write(genimage_cfg)

    print(f"Generated: {cfg_file}")


if __name__ == "__main__":
    main()
