plat: k3

tiboot3:
  defconfig: am62x_lpsk_r5_usbdfu_defconfig
  soc: am62x

tispl:
  defconfig: am62x_lpsk_a53_defconfig
  defconfig_fragments: am62x_android_a53.config
  soc: am62xx

spd: opteed

target_board: lite

optee:
  flags: CFG_ARM64_core=y
  optee_ta_path: vendor/ti/am62x/optee/ta

android:
  binaries_path: vendor/ti/am62x/bootloader/am62x-lp-sk-dfu

secure:
  gp: true
  hsfs: true
