plat: k3

tiboot3:
  defconfig: am62x_beagleplay_r5_defconfig
  defconfig_fragments: am62x_r5_usbdfu.config
  soc: am62x

tispl:
  defconfig: am62x_beagleplay_a53_defconfig
  defconfig_fragments: am62x_a53_android.config
  soc: am62xx

spd: opteed

target_board: lite

ti_lpm: true

optee:
  flags: CFG_ARM64_core=y
  optee_ta_path: vendor/ti/am62x/optee/ta
  plat: k3-am62x
  rpmb: false

android:
  binaries_path: vendor/ti/am62x/bootloader/2025.01/am625-beagleplay-dfu

secure:
  gp: true
  hsfs: false
