plat: k3

tiboot3:
  defconfig: am69_sk_r5_defconfig
  soc: j784s4

tispl:
  defconfig: am69_sk_a72_defconfig
  defconfig_fragments: am62x_a53_android.config
  soc: j784s4

spd: opteed

target_board: j784s4

uart: 0x8

optee:
  flags: CFG_ARM64_core=y
  optee_ta_path: vendor/ti/j784s4/optee/ta
  plat: k3-j784s4

android:
  binaries_path: vendor/ti/j784s4/bootloader/2025.01/am69-sk

secure:
  gp: false
  hsfs: true
